import dotenv from "dotenv";

dotenv.config();

const APP_PORT = process.env.APP_PORT || 4000;
const MONGO_DB_URI = process.env.MONGO_DB_URI;
const DEBUG_MODE = process.env.DEBUG_MODE;
const BASE_URL = process.env.BASE_URL;
const FRONTEND_URL = process.env.FRONTEND_URL;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const FORGET_PASSWORD_TOKEN_SECRET = process.env.FORGET_PASSWORD_TOKEN_SECRET;
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const GITHUB_USERNAME = process.env.GITHUB_USERNAME;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const NUMBER_OF_BOOKS_ALLOWED_TO_STUDENT = 3;
const NUMBER_OF_BOOKS_ALLOWED_TO_TEACHER = 5;

const NUMBER_OF_DAYS_OF_STUDENT = 365;
const NUMBER_OF_DAYS_OF_TEACHER_OR_HOD = 365;

export {
  APP_PORT,
  MONGO_DB_URI,
  FRONTEND_URL,
  DEBUG_MODE,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  FORGET_PASSWORD_TOKEN_SECRET,
  BASE_URL,
  CLOUDINARY_CLOUD_NAME,
  GITHUB_USERNAME,
  GITHUB_TOKEN,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  NUMBER_OF_BOOKS_ALLOWED_TO_STUDENT,
  NUMBER_OF_BOOKS_ALLOWED_TO_TEACHER,
  NUMBER_OF_DAYS_OF_STUDENT,
  NUMBER_OF_DAYS_OF_TEACHER_OR_HOD,
};
